# Default values for thelounge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: thelounge/thelounge
  pullPolicy: IfNotPresent


persistentVolumeClaimRetentionPolicy:
  whenDeleted: "Retain"
  whenScaled: "Retain"

storageClassName: "nfs-csi"
storageVolumeSize: "500Mi"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: irc.example.domain
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: signed-irc-tls
     hosts:
       - irc.example.domain

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
